/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.javalin.Javalin

class UserReqDto(
    val username: String,
    val password: String,
    val email: String
)

fun main() {
    val mapperConfig = MapperConfig()

    val app = Javalin.create { config ->
        config.jsonMapper(mapperConfig.gsonMapper)
    }.start(7070)

    app.get("/users") { ctx -> 
        ctx.result("fetchin users!");
    }

    app.post("/users") { ctx -> 
        val req = ctx.bodyAsClass(UserReqDto::class.java)
        val user = User(
            1,
            req.username,
            req.password,
            req.email
        )
        ctx.json(user);
    }
}
